name: box

shape_meta: &shape_meta # Reusable full shape metadata, including obs and action.
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: [3, 224, 224]
      type: rgb
      horizon: ${n_obs_steps}
    wrist_img:
      shape: [3, 224, 224]
      type: rgb
      horizon: ${n_obs_steps}
    agent_pos:
      shape: [6]
      type: low_dim
      horizon: ${n_obs_steps}
  action:
    shape: [15]
    horizon: ${n_action_steps}


dataset:
  _target_: dexpie.dataset.dp_dataset_image.DPDatasetImage
  zarr_path: data/box_zarr
  horizon: ${horizon}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 1000
  use_act_normal: False
  use_img: true
  use_wrist_img: true # Enable wrist image.
  use_depth: false
  use_relative_action: true
