defaults:
  - _self_
  - task: value_image

name: train_critic
_target_: diffusion_policy_3d.workspace.critic_workspace.CriticWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "debug"

n_obs_steps: 1
dataset_obs_steps: ${n_obs_steps}
num_bins: 201
v_min: -1
v_max:  0
max_length: 1000
fail_rate: 0.8 #尽量让失败轨迹的价值比最慢的轨迹价值低
use_image: true
policy:
  _target_: diffusion_policy_3d.policy.value_critic.ValueCritic
  shape_meta: ${shape_meta}
  model_name: 'r3m'
  pretrained: True
  frozen: False
  v_min: ${v_min}
  v_max: ${v_max}
  num_bins: ${num_bins}
  share_rgb_model: True
  transforms:
      - type: RandomCrop
        ratio: 0.95
      - _target_: torchvision.transforms.RandomRotation
        degrees:
          - -5.0
          - 5.0
        expand: false
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.4
        saturation: 0.5
        hue: 0.08

ema:
  _target_: diffusion_policy_3d.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 301
  gradient_accumulate_every: 1
  use_ema: True
  rollout_every: 200
  checkpoint_every: 100
  val_every: 100
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  save_video: False

logging:
  group: ${exp_name}
  id: null
  mode: online
  name: ${training.seed}
  project: humanoid_mimic
  resume: true
  tags:
  - train_diffusion_unet_hybrid
  - adroit

checkpoint:
  save_ckpt: False
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 2
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
